### ISSUE TITLE
Voucher error from console

### ISSUE THREAD

**Issue by 0xC1A551C** [badbones69/Vouchers#1]
I receive this error when I type the voucher command in the console with no player targeted.
Would be nice to have the abilities to give all players a voucher.

`voucher give partybox 1=> [02:32:22 WARN]: Unexpected exception while parsing console command "voucher give partybox 1"
org.bukkit.command.CommandException: Unhandled exception executing command 'voucher' in plugin Vouchers v1.7.2
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-565]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-565]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[patched_1.13.2.jar:git-Paper-565]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:696) ~[patched_1.13.2.jar:git-Paper-565]
at net.minecraft.server.v1_13_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:483) ~[patched_1.13.2.jar:git-Paper-565]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:440) ~[patched_1.13.2.jar:git-Paper-565]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-565]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-565]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.lang.NullPointerException
at me.badbones69.vouchers.Methods.isInventoryFull(Methods.java:333) ~[?:?]
at me.badbones69.vouchers.Main.onCommand(Main.java:153) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.2.jar:git-Paper-565]`

**Comment by 0xC1A551C** [comment]
I see the giveall command now.
